global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'command-pattern-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:5000']  
    scrape_interval: 5s