server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: command-pattern-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: command-pattern
          __path__: /var/log/command-pattern/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            commandType: commandType
            correlationId: correlationId
            executionTime: executionTime