// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCore8.CommandPattern.Infrastructure.Data;

#nullable disable

namespace NetCore8.CommandPattern.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241120213209_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetCore8.CommandPattern.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommandData = "{\"UserId\":1,\"Items\":[{\"ProductId\":1,\"Quantity\":1}]}",
                            CommandType = "CreateOrderCommand",
                            ExecutedAt = new DateTime(2024, 11, 15, 21, 32, 9, 279, DateTimeKind.Utc).AddTicks(2561),
                            IsSuccessful = true,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            CommandData = "{\"OrderId\":1,\"Amount\":1499.97}",
                            CommandType = "ProcessPaymentCommand",
                            ExecutedAt = new DateTime(2024, 11, 15, 21, 32, 9, 279, DateTimeKind.Utc).AddTicks(2562),
                            IsSuccessful = true,
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            CommandData = "{\"OrderId\":1,\"Status\":\"Completed\"}",
                            CommandType = "UpdateOrderCommand",
                            ExecutedAt = new DateTime(2024, 11, 15, 21, 32, 9, 279, DateTimeKind.Utc).AddTicks(2563),
                            IsSuccessful = true,
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("NetCore8.CommandPattern.Infrastructure.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 15, 21, 32, 9, 279, DateTimeKind.Utc).AddTicks(2464),
                            Status = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 17, 21, 32, 9, 279, DateTimeKind.Utc).AddTicks(2470),
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 18, 21, 32, 9, 279, DateTimeKind.Utc).AddTicks(2472),
                            Status = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 19, 21, 32, 9, 279, DateTimeKind.Utc).AddTicks(2473),
                            Status = 0,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("NetCore8.CommandPattern.Infrastructure.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            Price = 1299.99m,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            Price = 199.99m,
                            ProductId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            Price = 699.99m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            Price = 499.99m,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            Price = 299.99m,
                            ProductId = 5,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("NetCore8.CommandPattern.Infrastructure.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1499.97m,
                            OrderId = 1,
                            ProcessedAt = new DateTime(2024, 11, 15, 21, 32, 9, 279, DateTimeKind.Utc).AddTicks(2531),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 799.98m,
                            OrderId = 3,
                            ProcessedAt = new DateTime(2024, 11, 18, 21, 32, 9, 279, DateTimeKind.Utc).AddTicks(2532),
                            Status = 1
                        });
                });

            modelBuilder.Entity("NetCore8.CommandPattern.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            Username = "john.doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.doe@example.com",
                            Username = "jane.doe"
                        },
                        new
                        {
                            Id = 3,
                            Email = "admin@example.com",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("NetCore8.CommandPattern.Infrastructure.Entities.OrderItem", b =>
                {
                    b.HasOne("NetCore8.CommandPattern.Infrastructure.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetCore8.CommandPattern.Infrastructure.Entities.Payment", b =>
                {
                    b.HasOne("NetCore8.CommandPattern.Infrastructure.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetCore8.CommandPattern.Infrastructure.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
